# Generated by Django 3.2.9 on 2021-11-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(db_index=True, max_length=256)),
                ('arpabet_transcription', models.CharField(max_length=256)),
                ('ipa_transcription', models.CharField(max_length=256)),
                ('cz_transcription', models.CharField(max_length=256)),
                ('ru_transcription', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
